# Generated by Django 5.1.6 on 2025-03-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("handyman", "Handyman"),
                    ("cleaner", "Cleaner"),
                ],
                default="customer",
                max_length=10,
            ),
        ),
    ]
