# Generated by Django 4.2.3 on 2025-02-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cleaning", "0002_alter_cleaning_cleaner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cleaning",
            name="status",
            field=models.CharField(
                choices=[("A", "assigned"), ("P", "pending"), ("C", "completed")],
                default="P",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[("N", "not_checked"), ("I", "issue_found"), ("C", "checked")],
                default="N",
                max_length=1,
            ),
        ),
    ]
