# Generated by Django 4.2.3 on 2025-02-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cleaning", "0003_alter_cleaning_status_alter_review_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cleaning",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="cleaning",
            name="status",
            field=models.CharField(
                choices=[("A", "assigned"), ("C", "completed"), ("P", "pending")],
                default="P",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[("I", "issue_found"), ("C", "checked"), ("N", "not_checked")],
                default="N",
                max_length=1,
            ),
        ),
    ]
