# Generated by Django 4.2.3 on 2025-02-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cleaning", "0004_alter_cleaning_date_alter_cleaning_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cleaning",
            name="status",
            field=models.CharField(
                choices=[("C", "completed"), ("P", "pending"), ("A", "assigned")],
                default="P",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[("N", "not_checked"), ("C", "checked"), ("I", "issue_found")],
                default="N",
                max_length=1,
            ),
        ),
    ]
