# Generated by Django 5.1.6 on 2025-03-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cleaning", "0005_alter_cleaning_status_alter_review_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cleaning",
            name="status",
            field=models.CharField(
                choices=[("P", "pending"), ("C", "completed"), ("A", "assigned")],
                default="P",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[("I", "issue_found"), ("C", "checked"), ("N", "not_checked")],
                default="N",
                max_length=1,
            ),
        ),
    ]
