# Generated by Django 5.1.6 on 2025-03-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cleaning", "0010_alter_cleaning_status_alter_review_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cleaning",
            name="status",
            field=models.CharField(
                choices=[("C", "completed"), ("P", "pending"), ("A", "assigned")],
                default="P",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[("C", "checked"), ("I", "issue_found"), ("N", "not_checked")],
                default="N",
                max_length=1,
            ),
        ),
    ]
