# Generated by Django 5.1.6 on 2025-03-02 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cleaning", "0011_alter_cleaning_status_alter_review_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="cleaning",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="cleaning.cleaning",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[("N", "not_checked"), ("I", "issue_found"), ("C", "checked")],
                default="N",
                max_length=1,
            ),
        ),
    ]
