# Generated by Django 5.1.6 on 2025-03-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cleaning", "0012_alter_review_cleaning_alter_review_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cleaning",
            name="arrival_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cleaning",
            name="departure_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cleaning",
            name="status",
            field=models.CharField(
                choices=[("A", "assigned"), ("C", "completed"), ("P", "pending")],
                default="P",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[("C", "checked"), ("I", "issue_found"), ("N", "not_checked")],
                default="N",
                max_length=1,
            ),
        ),
    ]
