# Generated by Django 5.1.6 on 2025-03-12 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0004_arrival"),
        ("cleaning", "0014_alter_cleaning_status_alter_review_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cleaning",
            name="date",
        ),
        migrations.AddField(
            model_name="cleaning",
            name="arrival",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apartment.arrival",
            ),
        ),
        migrations.AlterField(
            model_name="cleaning",
            name="status",
            field=models.CharField(
                choices=[("A", "assigned"), ("C", "completed"), ("P", "pending")],
                default="P",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[("C", "checked"), ("N", "not_checked"), ("I", "issue_found")],
                default="N",
                max_length=1,
            ),
        ),
    ]
