# Generated by Django 5.1.6 on 2025-03-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cleaning", "0015_remove_cleaning_date_cleaning_arrival_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cleaning",
            name="status",
            field=models.CharField(
                choices=[("C", "completed"), ("A", "assigned"), ("P", "pending")],
                default="P",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[("I", "issue_found"), ("N", "not_checked"), ("C", "checked")],
                default="N",
                max_length=1,
            ),
        ),
    ]
