# Generated by Django 5.1.6 on 2025-03-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0002_remove_apartment_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="image",
            field=models.ImageField(blank=True, upload_to="apartment_images"),
        ),
    ]
