name: Trigger DigitalOcean Function Hourly

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour at minute 0
  workflow_dispatch:
    

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: Call DigitalOcean Function with Secret Code
        run: |
          curl -X POST "${{ secrets.FUNCTION_URL }}" -H "Content-Type: application/json" -d '{"special_code": "${{ secrets.SPECIAL_CODE }}"}'
